[package]
name = "basic"
version.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cube = { path = "../../cube", features = ["serde", "server"] }
tokio.workspace = true